module.exports = {
  docs: [
    'gettingstarted',
    {
      type: 'category',
      label: 'Accept Payments',
      collapsed: false,
      items: [
        'payment/links/index',
        'payment/qr/index',
        'payment/hosted/index',
        'payment/frames/index',
        'payment/mobile/index',
      ],
    },
    {
      type: 'category',
      label: 'Manage and Operate',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: '2-subscriptions' },
        { type: 'autogenerated', dirName: '3-manage' },
        { type: 'autogenerated', dirName: '7-golive' },
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'SDKs',
          collapsed: false,
          items: ['sdks/ios', 'sdks/android', 'sdks/php'],
        },
        {
          type: 'category',
          label: 'Webhooks',
          collapsed: false,
          items: [
            'track/webhooks',
            'track/configure-endpoint',
            'track/deliveries',
            'track/events',
          ],
        },
        {
          type: 'category',
          label: 'E-Commerce',
          collapsed: false,
          items: [
            'payment/ecomm/opencart',
            'payment/ecomm/shopify',
            'payment/ecomm/woocommerce',
          ],
        },
        {
          type: 'category',
          label: 'Third-Party Apps',
          collapsed: false,
          items: ['payment/apps/xero', 'payment/apps/zoho'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Resources and Updates',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: '8-resources' }],
    },
  ],
};
