module.exports = {
  guides: [
    {
      type: 'category',
      label: 'Get Started',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: '1-getting-started' }],
    },
    {
      type: 'category',
      label: 'Manage Your Account',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: '2-your-account' }],
    },
    {
      type: 'category',
      label: 'Accept Payments',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: '6-online-payment' }],
    },
    {
      type: 'category',
      label: 'Funds and Operations',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: '10-funds-and-payments' }],
    },
  ],
};
